apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.consumer.name }}
spec:
  replicas: {{ .Values.consumer.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.consumer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.consumer.name }}
    spec:
      containers:
      - name: consumer
        image: {{ .Values.consumer.image }}
        env:
        - name: KAFKA_USER
          value: "{{ .Values.consumer.kafkaUser }}"
        - name: KAFKA_PASS
          value: "{{ .Values.consumer.kafkaPass }}"        