apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.producer.name }}
spec:
  replicas: {{ .Values.producer.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.producer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.producer.name }}
    spec:
      containers:
      - name: producer
        image: {{ .Values.producer.image }}
        env:
        - name: CAT_API_KEY
          value: "{{ .Values.producer.catApiKey }}"
        - name: DOG_API_KEY
          value: "{{ .Values.producer.dogApiKey }}"
        - name: KAFKA_USER
          value: "{{ .Values.producer.kafkaUser }}"
        - name: KAFKA_PASS
          value: "{{ .Values.producer.kafkaPass }}"      