replicaCount: 3

kafkaConfig:
  processRoles: "broker,controller"
  logDirs: "/var/lib/kafka/data"
  autoCreateTopicsEnable: "true"
  nodeId: 0
  #controllerQuorumVoters: "1@127.0.0.1:9093"

zookeeper:
  enabled: false

configurationOverrides:
  "listeners": "PLAINTEXT://:9092"
  #"advertised.listeners": "PLAINTEXT://$(MY_POD_IP):9092"
  "zookeeper.connect": ""

service:
  type: ClusterIP
  port: 9092

resources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "2Gi"
