replicaCount: 3

zookeeper:
  enabled: false

kafkaConfig:
  brokerId: 0
  logDirs: "/var/lib/kafka/data"
  autoCreateTopicsEnable: true
  listeners: "PLAINTEXT://:9092"
  advertisedListeners: "PLAINTEXT://$(MY_POD_IP):9092"
  processRoles: "broker,controller"
  controllerQuorumVoters: "0@localhost:9093,1@localhost:9093,2@localhost:9093"
  zookeeperConnect: ""

service:
  type: ClusterIP
  port: 9092

resources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "2Gi"