replicaCount: 3

zookeeper:
  enabled: false

kafkaConfig:
  brokerId: 0
  node_id: 0 
  controllerListenerNames: "CONTROLLER"
  logDirs: "/var/lib/kafka/data"
  autoCreateTopicsEnable: true
  listeners: "PLAINTEXT://:9092,CONTROLLER://:9093"
  advertisedListeners: "PLAINTEXT://$(POD_IP):9092,CONTROLLER://$(POD_IP):9093"
  processRoles: "broker,controller"
  controllerQuorumVoters: "0@$(POD_IP):9093,1@$(POD_IP):9093,2@$(POD_IP):9093"
  zookeeperConnect: ""


service:
  type: ClusterIP
  port: 9092

resources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "2Gi"
