kafka:
  ssl: false
  sasl:
    enabled: false

replicaCount: 3

kafkaConfig:
  brokerId: 0
  logDirs: "/var/lib/kafka/data"
  autoCreateTopicsEnable: "true"

auth:
  enabled: false
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    mechanism: ""
    interBrokerMechanism: ""

service:
  type: ClusterIP
  port: 9092

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

livenessProbe:
  tcpSocket:
    port: 9092
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  tcpSocket:
    port: 9092
  initialDelaySeconds: 5
  periodSeconds: 10
