
replicaCount: 3

## Configure Kafka with PLAINTEXT listeners and no security
auth:
  enabled: false
  clientProtocol: plaintext
  interBrokerProtocol: plaintext

## Kafka configuration
config:
  advertised.listeners: PLAINTEXT://$(MY_POD_NAME).my-kafka-headless.default.svc.cluster.local:9092
  listeners: PLAINTEXT://:9092
  auto.create.topics.enable: "false"  # Disable auto-creation to manage topics via job

## Service configurations
service:
  type: ClusterIP
  port: 9092

## Persistence settings, adjust based on your needs, disabling for simplicity
persistence:
  enabled: false

## Resource configurations, adjust as necessary
resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"