replicaCount: 3

kafkaConfig:
  brokerId: 0
  logDirs: "/var/lib/kafka/data"
  autoCreateTopicsEnable: "true"

auth:
  enabled: false
  clientProtocol: plaintext
  interBrokerProtocol: plaintext

extraEnvVars:
  - name: KAFKA_LOG4J_LOGGERS
    value: "kafka.controller=DEBUG,kafka.server=DEBUG,state.change.logger=DEBUG"

# resources:
#   requests:
#     cpu: "1"
#     memory: "1Gi"
#   limits:
#     cpu: "2"
#     memory: "2Gi"

service:
  type: ClusterIP
  port: 9092

# livenessProbe:
#   tcpSocket:
#     port: 9092
    
# readinessProbe:
#   tcpSocket:
#     port: 9092