replicaCount: 3  # Ensures high availability by deploying 3 brokers

# Authentication settings, disabled in this case
auth:
  enabled: false

# Persistence settings, disabled for simplicity and stateless operation
persistence:
  enabled: false

# Kafka configuration
kafkaConfig:
  brokerId: 0
  logDirs: "/var/lib/kafka/data"
  autoCreateTopicsEnable: "true"
  listeners: "PLAINTEXT://:9092,CONTROLLER://:9093"
  advertisedListeners: "PLAINTEXT://$(MY_POD_IP):9092"
  controllerQuorumVoters: "0@localhost:9093,1@localhost:9093,2@localhost:9093"
  kraftClusterId: "my-kafka-cluster"
  interBrokerProtocolVersion: "3.4"

# Topic configuration to be used in the initContainers for creating topics
topics:
  - name: test-topic
    partitions: 3
    replicationFactor: 3

# Resource allocations for Kafka pods
resources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "2Gi"

# Service configuration for accessing Kafka within the cluster
service:
  type: ClusterIP
  port: 9092

# Liveness probe configuration to check the health of Kafka pods
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

# Readiness probe configuration to check if Kafka pods are ready to serve requests
readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 6
