
# apiProducer:
#   replicaCount: 1
#   image:
#     repository: dorbivas/kafka-producer-test
#     tag: latest
#     pullPolicy: Always
#   name: api-producer
#   service:
#     type: ClusterIP
#     port: 8080

# kafkaConsumer:
#   replicaCount: 1
#   image:
#     repository: dorbivas/kafka-consumer
#     tag: latest
#     pullPolicy: IfNotPresent
#   name: kafka-consumer
#   service:
#     type: ClusterIP
#     port: 8081


# ## Kafka configuration tailored for KRaft mode with essential settings
# kafka:
#   replicaCount: 1  # Single broker for simplicity

#   ## Disable all security features
#   extraEnvVars:
#     - name: KAFKA_ENABLE_KRAFT
#       value: "yes"
#     - name: KAFKA_CFG_PROCESS_ROLES
#       value: "broker,controller"
#     - name: KAFKA_CFG_LISTENERS
#       value: "PLAINTEXT://:9092"
#     - name: KAFKA_CFG_ADVERTISED_LISTENERS
#       value: "PLAINTEXT://$(MY_POD_IP):9092"
#     - name: KAFKA_BROKER_ID
#       value: "1"
#     - name: ALLOW_PLAINTEXT_LISTENER
#       value: "yes"
#     - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
#       value: "true"

#   ## Listener configuration
#   service:
#     type: ClusterIP
#     port: 9092  # Default port for Kafka

#   ## Resource settings (adjust as necessary for your environment)
#   resources:
#     requests:
#       memory: "512Mi"
#       cpu: "500m"
#     limits:
#       memory: "1024Mi"
#       cpu: "1000m"



apiVersion: v2
name: my-kafka
version: 0.1.0

## Producer configuration
apiProducer:
  replicaCount: 1
  image:
    repository: dorbivas/kafka-producer-test
    tag: latest
    pullPolicy: Always
  name: api-producer
  service:
    type: ClusterIP
    port: 8080

## Consumer configuration
kafkaConsumer:
  replicaCount: 1
  image:
    repository: dorbivas/kafka-consumer
    tag: latest
    pullPolicy: IfNotPresent
  name: kafka-consumer
  service:
    type: ClusterIP
    port: 8081

kafka:
  replicaCount: 1  # Single broker for simplicity

  ## Disable all security features
  extraEnvVars:
    - name: KAFKA_ENABLE_KRAFT
      value: "yes"
    - name: KAFKA_CFG_PROCESS_ROLES
      value: "broker,controller"
    - name: KAFKA_CFG_LISTENERS
      value: "PLAINTEXT://:9092"
    - name: KAFKA_CFG_ADVERTISED_LISTENERS
      value: "PLAINTEXT://$(MY_POD_IP):9092"
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: ALLOW_PLAINTEXT_LISTENER
      value: "yes"
    - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
      value: "true"

  ## Service configuration
  service:
    type: ClusterIP
    port: 9092  # Default port for Kafka

  ## Resource settings (adjust as necessary for your environment)
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"