apiProducer:
  replicaCount: 1
  image:
    repository: dorbivas/kafka-producer-test
    tag: latest
    pullPolicy: Always
  name: api-producer
  service:
    type: ClusterIP
    port: 8080

kafkaConsumer:
  replicaCount: 1
  image:
    repository: dorbivas/kafka-consumer
    tag: latest
    pullPolicy: IfNotPresent
  name: kafka-consumer
  service:
    type: ClusterIP
    port: 8081

zookeeper:
  enabled: true
kafka:
  replicaCount: 3  # Adjust the number of Kafka brokers as needed
  controller:
    replicaCount: 0  # No controllers in Zookeeper mode
  kraft:
    enabled: false  # Important: Ensure KRaft mode is disabled
  config:
    log.message.format.version: "2.8"


