apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiProducer.name }}
spec:
  type: {{ .Values.apiProducer.service.type }}
  ports:
    - port: {{ .Values.apiProducer.service.port }}
      targetPort: 80
  selector:
    app: {{ .Values.apiProducer.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafkaConsumer.name }}
spec:
  type: {{ .Values.kafkaConsumer.service.type }}
  ports:
    - port: {{ .Values.kafkaConsumer.service.port }}
      targetPort: 80
  selector:
    app: {{ .Values.kafkaConsumer.name }}
