apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  server.properties: |
    broker.id={{ .Values.kafkaConfig.brokerId }}
    log.dirs={{ .Values.kafkaConfig.logDirs }}
    listeners={{ .Values.kafkaConfig.listeners }}
    advertised.listeners={{ .Values.kafkaConfig.advertisedListeners }}
    process.roles={{ .Values.kafkaConfig.processRoles }}
    controller.quorum.voters={{ .Values.kafkaConfig.controllerQuorumVoters }}
    zookeeper.connect={{ .Values.kafkaConfig.zookeeperConnect }}
    auto.create.topics.enable={{ .Values.kafkaConfig.autoCreateTopicsEnable }}