apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  server.properties: |
    broker.id={{ .Values.kafkaConfig.nodeId }}
    log.dirs={{ .Values.kafkaConfig.logDirs }}
    auto.create.topics.enable={{ .Values.kafkaConfig.autoCreateTopicsEnable }}
    listeners=PLAINTEXT://:9092
    #advertised.listeners=PLAINTEXT://$(MY_POD_IP):9092
    process.roles={{ .Values.kafkaConfig.processRoles }}
    node.id={{ .Values.kafkaConfig.nodeId }}
    controller.quorum.voters=$(MY_POD_IP):9093#{{ .Values.kafkaConfig.controllerQuorumVoters }}
    # Disable ZooKeeper
    zookeeper.connect=
;l