apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: "bitnami/kafka:latest"
        ports:
        - name: kafka
          containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "{{ .Values.kafkaConfig.nodeId }}"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: kafka-config
          mountPath: /opt/bitnami/kafka/config/server.properties
          subPath: server.properties
        - name: data
          mountPath: /var/lib/kafka/data
      volumes:
      - name: kafka-config
        configMap:
          name: kafka-config
      - name: data
        emptyDir: {}
