apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kafka.fullname" . }} 
spec:
  serviceName: "{{ include "kafka.fullname" . }}-headless"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kafka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kafka.labels" . | nindent 8 }}
    spec:
      containers:
      - name: kafka
        image: "bitnami/kafka:latest"
        ports:
        - name: kafka
          containerPort: 9092
        envFrom:
        - configMapRef:
            name: kafka-config
        livenessProbe:
          tcpSocket:
            port: 9092
        readinessProbe:
          tcpSocket:
            port: 9092
        volumeMounts:
        - name: data
          mountPath: /var/lib/kafka/data
      volumes:
      - name: data
        emptyDir: {}