apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-create-topics
  labels:
    app: kafka
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: create-topics
        image: bitnami/kafka:latest
        command:
          - sh
          - -c
          - |
            kafka-topics.sh --bootstrap-server my-kafka-headless.default.svc.cluster.local:9092 --create --topic test-topic --partitions 3 --replication-factor 3
      restartPolicy: Never